import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

import { auth } from "@/auth";
import DashboardLayout from "@/components/layouts/dashboard-layout";
import LandingLayout from "@/components/layouts/landing-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-sm bg-white dark:bg-zinc-900 text-zinc-800 dark:text-zinc-100 transition-colors duration-300 ease-in-out`}
      >
        <Providers>
          {session ? (
            <DashboardLayout>{children}</DashboardLayout>
          ) : (
            <LandingLayout>{children}</LandingLayout>
          )}
        </Providers>
      </body>
    </html>
  );
}
